// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WzkImgCut: typeof import('./src/components/wzkImgCut/index.vue')['default']
    WzkLogin: typeof import('./src/components/wzkLogin/index.vue')['default']
    WzkUploadRef: typeof import('./src/components/wzkUploadRef/index.vue')['default']
  }
}
